### ISSUE TITLE
Como rodar na versão mobile?

### ISSUE THREAD

**Issue by fernandogobah** [fadoaglauss/stremio-brazilian-addon#1]
Olá, como instalar na versão mobile?

**Comment by fadoaglauss** [comment]
Ainda estamos concluindo o projeto, logo adicionarei um tutorial no readme

**Comment by fadoaglauss** [comment]
Abra esse url https://stremio-brazilian-addon.herokuapp.com/ no navegador do seu celular e adicione o addon.

**Comment by fernandogobah** [comment]
Instalado, mas não faz link pra nenhum filme.

**Comment by fadoaglauss** [comment]
Desculpa a demora a responder, acredito que agora esteja funcionando e sugiro reinstala-lo, pois fizemos diversar modificações.
Na versão anterior não estava _linkando_, como você mencionou, pois optamos por utilizar catálogos independentes dos oficiais, mas graças a seu _feedback_ nos decidimos em desfazer essa alteração e agora já deve funcionar. 
Entretanto, ainda é possível encontrar o nosso catálogo na íntegra ao navegar para a seção "Descubra -> Filmes -> Filmes Dublados".

[13:22, 03/05/2020] Victor Guerra Veloso: Além disso atente-se ao resultado da busca. Os filmes dublados devem aparecer juntos com os demais filmes, além de terem sua própria listagem se você scrolar para baixo!

**Comment by fernandogobah** [comment]
Testado, rodando 100%. Parabens ao trabalho ficou muito bom.

Em ter., 5 de mai. de 2020 às 16:34, Fadoa Glauss V. <
notifications@github.com> escreveu:

**Comment by fernandogobah** [comment]
Testado, rodando 100%. Parabens ao trabalho ficou muito bom.

**Comment by fernandogobah** [comment]
Testado, rodando 100%. Parabens ao trabalho ficou muito bom. Apenas um detalhe que notei que diversos títulos não retorna nenhum fetch, se precisar de alguns sites como fonte para acrestar a busca posso indicar alguns.
