### ISSUE TITLE
Ao pesquisar por nomes, nenhum filtro é aplicado

### ISSUE THREAD

**Issue by victorgveloso** [fadoaglauss/stremio-brazilian-addon#3]
**Contexto:** Ao buscar um nome de filme resultados são aplicados filtros em cada catálogo com suporte a busca.
**Problema:** Apesar do catálogo ser apresentado, nenhum filtro é aplicado. Sendo o resultado da busca indiferente ao texto inserido no campo de busca.
**Resultado esperado:** Os filmes com nome mais próximo ao buscado deve aparecer primeiro no resultado da busca e filmes cujo nome nada se assemelha ao buscado não devem aparecer.

**Comment by fadoaglauss** [comment]
Resolve
