### ISSUE TITLE
Fix `publishToCentral()`

### ISSUE THREAD

**Issue by danamag** [fadoaglauss/stremio-brazilian-addon#6]
This line:
https://github.com/fadoaglauss/stremio-brazilian-addon/blob/bc9911aca3caa189c93c95463954bb76c36bee4f/src/index.js#L57

Needs to be:
```javascript
publishToCentral('https://stremio-brazilian-addon.herokuapp.com/manifest.json')
```

**Comment by victorgveloso** [comment]
Thanks for the little tip. I've just added it to master branch. Soon it'll get to production!
